[car]
# Relative path to the model file used for the car. Relative to the folder where this .ini is.
model = spec17.gltf
# Name of object in the model file that will be used as a visual for all wheels. All other wheels will be hidden.
wheelObject = wheel_tarmac

[physics]
# Mass of the whole car (including wheels)
mass = 1190
# How much the car's body sliding over world surfaces will have friction. I have 
collisionFriction = 0.9

[handling]
# Yaw angular acceleration for steering if front wheels are in contact with the ground
steerMult = 7000
# Negative yaw angular acceleration (drag) if front wheels are in contact with the ground
steerDragMult = 4000
# Vertical offset of an application point of all forces
forcePointOffset = 0

[suspension]
springMult = 80000
dampMult = 3000
# Use a value between 0-1, more than 1 can cause instability
rollbarStiffness = 0.5

[geometry]
# Distance between front and read axle
wheelBase = 2.55
# Distance between left and right wheels
wheelTrack = 1.7
wheelRadius = 0.325
# These following values are hard to explain, press F1 in game to show debug lines, and then move the values in Dev GUI and hopefully they will make sense.
# Height from origin where raycast for wheels begins. This should ALWAYS be inside the car's collision convex hull, otherwise the wheels might sink through the ground. 
raycastOriginheight = -0.2
# Maximum height the visual wheel can be at. This is used to prevent the graphical wheel to go through fenders, even if physically, the wheel still compresses.
wheelMaxHeight = -0.07
# Maximum lenght of the suspension from the origin point. This is the raycast length.
suspensionTravel = 0.6
# Height at which the springs are fully extended. Keep at or slightly above suspensionTravel to prevent stability issues.
rideHeight = 0.43

[drivetrain]
# Unused
brakePoint = 0,0,0
tractionPoint = 0,0,0
# Actually unused:
driveInertia = 0.02
# Mass of a single wheel that is used in calculating total driveline inertia
wheelMass = 50
brakeFrictionTorque = 1950
rollingFriction = 0.01

[engine]
# Maximum RPM against which all the values are calculated. This is also the top value of the HUD RPM gauge
maxRPM = 9000
# Maximum torque of the engine (without friction)
maxTorque = 420
# 20 torque steps, the first being at 0 RPM, and 20th being at maxRPM. Always use normalized values (between 0-1) and then scale them with maxTorque
torqueCurve = 0, 0.083333, 0.208333, 0.388889, 0.569444, 0.708333, 0.805556, 0.868056, 0.902778, 0.944444, 0.944444, 0.993056, 1, 0.993056, 0.9375, 0.881944, 0.847223, 0.784722, 0.666666, 0
# RPM at which rev limiter will start turning throttle off
limiterRPM = 8500
idleRPM = 2000
# Once the RPM reaches the rev limiter, it shuts off throttle, and this is how long it takes for the throttle to come back on
limiterBurstDuration = 0.055
# Angular inertia of the engine in kg*m2. Typically between 0.1 and 0.25.
engineInertia = 0.15

[clutch]
# Frequency of the spring that the clutch will bounce at in Hz
wobbleFrequency = 6
# Damping ratio of the clutch spring, 0 for no damping, 1 for fully damped
wobbleDampingRatio = 0.26

[gearbox]
# Total number of gears, including reverse and neutral, so 2 + number of forward gears. So, a 6 speed car should have ratiosCount = 8 
ratiosCount = 8
# Gear ratios. You can remove the top gears that are unused 
ratios = -2.142, 0, 2.6, 1.85, 1.42, 1.15, 0.95, 0.78, 1, 1, 1, 1
# Final gear ratio, typically at the differential (or multiple diffs) 
finalRatio = 6.5
# RPM at which automatic gearbox will downshift
autoDownshiftRPM = 5458
# RPM at which automatic gearbox will upshift. Note that it will not upshift at high wheel slip.
autoUpshiftRPM = 8200

[tire]
# Final multiplier for longitudinal (long) and lateral (side). Would be best and most realistic if it was kept at 1, but you can use these as final parameters to tweak the feel.
longGripMult = 1
sideGripMult = 1

# Following are 4-parameter Pacejka coefficients. See tire plot window in the Dev GUI for easy visual editing of these numbers.

# Longitudinal parameters:

# aka stiffness
tire_b = 10
# aka shape
tire_c = 1.1
# aka peak
tire_d = 0.7
# aka curvature
tire_e = 0.97

# Lateral parameters:

tire_side_b = 1.5
tire_side_c = 1.6
tire_side_d = 2
tire_side_e = -0.2

[aero]
# Air drag multiplier, which formula is `airDragMult * velocity^2`. So, this corresponds to combined `CdRA/2` part of a classic air drag formula: coefficient * air_density * frontal_area * velocity^2 / 2
airDragMult = 0.62

[graphics]
lightsIntensity = 1
frontLightsPosition = 0, 0.4, 1.2
rearLightsPosition = 0, 0.5, -1.6

# How many steps the wheel blur at speed will create. Up to 8 steps.
wheelMotionBlurSteps = 4
# At which speed does each blur step transition in kmh
wheelMotionBlurThresholds = 12, 35, 80, 160

[audio]
# Engine RPM at which the pitch of the sound clip used for the engine is 1
enginePitchReferenceRPM = 6150
# Driveshaft RPM at which the pitch of the sound clip used for the transmission whine is 1
transmissionPitchReferenceRPM = 660
# Multiplier for the transmission whine, which depends on the difference between angular velocities before and after the clutch 
audioTransmissionDiffSlipFactor = 10

# All sounds are loaded 
# File name (without extension) for the audio clip which will be used for following sounds.
engineOnHiClip = engine_hi
transmissionClip = transmission_clean
turboClip = turbine

gearUpshiftClip = gear_squeak
gearDownshiftClip = shift

[camera]
onboardCameraPosition = 0.4, 0.7, 0.1
orbitCameraLookAtOffset = 0, 0.5, 0